### ISSUE TITLE
Azure_CLI for local dev gives Access is denied: 'C:\\Windows\\system32\\config\\systemprofile\\.azure'

### ISSUE THREAD

**Issue by degrover-cn** [Azure-Samples/app-service-msi-keyvault-dotnet#11]
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I have the AZ CLI open,  az account get-access-token shows the right account, Visual Studio running as admin, but the CLI validation fails with  

PermissionError: [WinError 5] Access is denied: 'C:\\Windows\\system32\\config\\systemprofile\\.azure'

### Any log messages given by the failure
> NO

### Expected/desired behavior
> it gets my token from Azure CLI

### OS and Version?
> Windows 10 Enterprise v 1809
### Versions
>

### Mention any other details that might be useful
Please document how to troubleshoot this error.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by harsu-ag** [comment]
Any update on this issue?

**Comment by bbarman4u** [comment]
I am facing the same issue.

**Comment by Dev28041989** [comment]
Trying to open cmd and executing azure cli commands through c#, Getting below error
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/__main__.py", line 38, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 903, in get_default_cli
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/azlogging.py", line 30, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 25, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/__init__.py", line 18, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/config.py", line 40, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/util.py", line 115, in ensure_dir
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/util.py", line 112, in ensure_dir
  File "os.py", line 223, in makedirs
PermissionError: [WinError 5] Access is denied: 'C:\\windows\\system32\\config\\systemprofile\\.azure'
